name: rural_roots_demo1
description: "Aplicación para conectar agricultores con compradores locales"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.2
  
  # Navigation
  go_router: ^14.6.2
  
  # Networking
  http: ^1.2.2
  
  # Local Storage
  shared_preferences: ^2.3.3
  
  # Maps
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.2
  
  # Image Handling
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  
  # Environment Variables
  flutter_dotenv: ^5.2.1
  
  # Utilities
  intl: ^0.19.0
  equatable: ^2.0.7
  
  # UI
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Testing
  mockito: ^5.4.4
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - .env
